# \u9879\u76EE\u76F8\u5173\u914D\u7F6E
ruoyi:
  # \u540D\u79F0
  name: RuoYi
  # \u7248\u672C
  version: 4.1.0
  # \u7248\u6743\u5E74\u4EFD
  copyrightYear: 2019
  # \u5B9E\u4F8B\u6F14\u793A\u5F00\u5173
  demoEnabled: true
  # \u6587\u4EF6\u8DEF\u5F84 \u793A\u4F8B\uFF08 Windows\u914D\u7F6ED:/ruoyi/uploadPath\uFF0CLinux\u914D\u7F6E /home/ruoyi/uploadPath\uFF09
  profile: D:/ruoyi/uploadPath
  # \u83B7\u53D6ip\u5730\u5740\u5F00\u5173
  addressEnabled: true

spring:
  application:
    name: excel
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.53.217.86:3306/lzx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Lzx1922026241@
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      removeAbandoned: true
      removeAbandonedTimeout: 180
      logAbandoned: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      filters: stat,wall,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        allow: #127.0.0.1
        deny: #127.0.0.1
        reset-enable: false
        login-username: admin
        login-password: admin

server:
  port: 8856
  servlet:
    context-path: /excel

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.lzx.excel.entity
  global-config:
    banner: false
    db-config:
      id-type: UUID
      field-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: mybatis.sql.

